---
- name: update system
  apt:
    name: "*"
    update_cache: yes
    state: latest 
    
- name: apt install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  with_items:
    - bluez
    - bluez-tools
    - bluez-hcidump
    - pi-bluetooth
    - podman
